from tkinter import *

class CGPACalculator:
    def __init__(self) -> None:
        window = Tk()
        window.title(" CGPA Calculator - Regulation 2019 (CBCS) ")
        window.geometry("500x500")
        Label(window, text=" Semesters ",justify=CENTER).grid(row=1,column=1)
        Label(window, text=" Credit Points ",justify=CENTER).grid(row=1,column=2)
        Label(window, text=" GPA ",justify=CENTER).grid(row=1,column=3)  
        Label(window, text=" Semester 1 ",justify=CENTER).grid(row=2,column=1)
        Label(window, text=" Semester 2 ",justify=CENTER).grid(row=3,column=1)
        Label(window, text=" Semester 3 ",justify=CENTER).grid(row=4,column=1) 
        Label(window, text=" Semester 4 ",justify=CENTER).grid(row=5,column=1)
        Label(window, text=" Semester 5 ",justify=CENTER).grid(row=6,column=1)
        Label(window, text=" Semester 6 ",justify=CENTER).grid(row=7,column=1)
        Label(window, text=" Semester 7 ",justify=CENTER).grid(row=8,column=1)
        Label(window, text=" Semester 8 ",justify=CENTER).grid(row=9,column=1)

        Label(window, text="CGPA",justify=CENTER).grid(row=12,column=1)
        Label(window, text="Total Credit Points",justify=CENTER).grid(row=13,column=1)
        self.cgpa = StringVar()
        ngpa = Label(window, textvariable=self.cgpa).grid(row=12,column=2)
        self.tcp = StringVar()
        ntcp = Label(window, textvariable=self.tcp).grid(row=13,column=2)
        gpacompute = Button(window, text="Calculate CGPA",command=self.calculatecgpa).grid(row=15,column=2)
        self.cp1 = StringVar()
        Entry(window, textvariable=self.cp1).grid(row=2,column=2)
        self.cp2 = StringVar()
        Entry(window, textvariable=self.cp2).grid(row=3,column=2)
        self.cp3 = StringVar()
        Entry(window, textvariable=self.cp3).grid(row=4,column=2)
        self.cp4 = StringVar()
        Entry(window, textvariable=self.cp4).grid(row=5,column=2)
        self.cp5 = StringVar()
        Entry(window, textvariable=self.cp5).grid(row=6,column=2)
        self.cp6 = StringVar()
        Entry(window, textvariable=self.cp6).grid(row=7,column=2)
        self.cp7= StringVar()
        Entry(window, textvariable=self.cp7).grid(row=8,column=2)
        self.cp8= StringVar()
        Entry(window, textvariable=self.cp8).grid(row=9,column=2)
       
        self.g1 = StringVar()
        Entry(window, textvariable=self.g1).grid(row=2,column=3)
        self.g2 = StringVar()
        Entry(window, textvariable=self.g2).grid(row=3,column=3)
        self.g3 = StringVar()
        Entry(window, textvariable=self.g3).grid(row=4,column=3)
        self.g4 = StringVar()
        Entry(window, textvariable=self.g4).grid(row=5,column=3)
        self.g5 = StringVar()
        Entry(window, textvariable=self.g5).grid(row=6,column=3)
        self.g6 = StringVar()
        Entry(window, textvariable=self.g6).grid(row=7,column=3)
        self.g7 = StringVar()
        Entry(window, textvariable=self.g7).grid(row=8,column=3)
        self.g8 = StringVar()
        Entry(window, textvariable=self.g8).grid(row=9,column=3)
        
        window.mainloop()
    
    def calculatecgpa (self):
        total = int(self.cp1.get()) * float(self.g1.get()) + int(self.cp2.get()) * float(self.g2.get()) + int(self.cp3.get()) * float(self.g3.get()) + int(self.cp4.get()) * float(self.g4.get()) + int(self.cp5.get()) * float(self.g5.get()) + int(self.cp6.get()) * float(self.g6.get()) + int(self.cp7.get()) * float(self.g7.get()) + int(self.cp8.get()) * float(self.g8.get()) 
        totalcp = int(self.cp1.get()) + int(self.cp2.get()) + int(self.cp3.get()) + int(self.cp4.get()) + int(self.cp5.get()) + int(self.cp6.get()) + int(self.cp7.get()) + int(self.cp8.get()) 
        cg = total / totalcp
        g = round (cg,2)
        self.cgpa.set(g)
        self.tcp.set(totalcp)
        
    
CGPACalculator()
